name: DevKit CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install DevKit
        run: |
          python -m pip install --upgrade pip
          pip install -e ./tools/devkit

      - name: Run Linting
        run: |
          devkit lint check
          devkit lint fix

      - name: Run Tests
        run: |
          devkit test run

      - name: Analyze Code Changes
        id: analyze
        run: |
          devkit version analyze > version_changes.txt
          echo "changes=$(cat version_changes.txt)" >> $GITHUB_OUTPUT

  security-scan:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install DevKit
        run: |
          python -m pip install --upgrade pip
          pip install -e ./tools/devkit

      - name: Version Check
        run: |
          devkit version check

      - name: Security Scan
        run: |
          devkit docker scan .

      - name: Generate SBOM
        run: |
          devkit docker sbom .

      - name: Update Version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Get version change type from pre-commit job
          VERSION_CHANGE=$(cat version_changes.txt)
          case $VERSION_CHANGE in
            "major") devkit version bump major ;;
            "minor") devkit version bump minor ;;
            "patch") devkit version bump patch ;;
            *) echo "No version change needed" ;;
          esac
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "chore: bump version [skip ci]"
          git push

  deploy:
    needs: security-scan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install DevKit
        run: |
          python -m pip install --upgrade pip
          pip install -e ./tools/devkit

      - name: Deploy to GitHub Pages
        run: |
          devkit deploy github-pages 