name: Pre-commit Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install DevKit
        run: |
          python -m pip install --upgrade pip
          pip install -e ./tools/devkit

      - name: Run Linting
        run: |
          devkit lint check
          devkit lint fix

      - name: Run Tests
        run: |
          devkit test run

      - name: Analyze Code Changes
        id: analyze
        run: |
          devkit version analyze > version_changes.txt
          echo "changes=$(cat version_changes.txt)" >> $GITHUB_OUTPUT 