name: Pre-commit Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g alex write-good

      - name: Run ESLint
        run: npm run lint

      - name: Run HTML validation
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              execSync('npx htmlhint "**/*.html"', { stdio: 'inherit' });
            } catch (error) {
              console.error('HTML validation failed');
              process.exit(1);
            }

      - name: Run CSS validation
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              execSync('npx stylelint "**/*.css"', { stdio: 'inherit' });
            } catch (error) {
              console.error('CSS validation failed');
              process.exit(1);
            }

      - name: Check writing quality
        run: |
          # Check for insensitive or inconsiderate writing
          alex "**/*.{html,md}" --quiet
          
          # Check for better writing suggestions
          write-good "**/*.{html,md}" --no-passive

      - name: Analyze Code Changes
        id: analyze
        run: |
          # Simple version bump based on commit messages
          if git log -1 --pretty=%B | grep -q "BREAKING CHANGE"; then
            echo "changes=major" >> $GITHUB_OUTPUT
          elif git log -1 --pretty=%B | grep -q "feat:"; then
            echo "changes=minor" >> $GITHUB_OUTPUT
          else
            echo "changes=patch" >> $GITHUB_OUTPUT
          fi 