name: Pre-commit Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g prettier htmlhint stylelint svgo

      - name: Format check
        run: |
          npx prettier --check "**/*.{js,html,css,svg}"

      - name: Lint JavaScript
        run: npx eslint .

      - name: Validate HTML
        run: npx htmlhint "**/*.html"

      - name: Validate CSS
        run: npx stylelint "**/*.css"

      - name: Validate SVGs
        run: |
          npx svgo --check "**/*.svg"

      - name: Check writing quality
        run: |
          npm install -g alex write-good
          alex .
          write-good "**/*.md" 